- name: Start docker image
  command: ./pi_box start
  args:
    chdir: ~/CodePlayerBox/docker-pi-box/script
  register: command_result
  changed_when: False
#- debug: msg="{{ command_result.stdout }}"

- name: Check docker status
  command: docker ps -f name=docker-pi-box -q
  register: command_result
  failed_when: command_result.stdout|length < 1
  changed_when: False
- debug: msg="{{ command_result.stdout }}"
