- name: Upload docker to rpi
  synchronize:
    src: ../docker/
    dest: ~/CodePlayerBox/docker-pi-box/
    rsync_opts:
      - "--delete"
      - "--exclude=.DS_Store"
      - "--exclude=script"
      - "--exclude=node_modules"

- name: Upload script to rpi
  synchronize:
    src: ../script/
    dest: ~/CodePlayerBox/docker-pi-box/script
    rsync_opts:
      - "--delete"
      - "--exclude=.DS_Store"

